name: CI - Build, Lint, and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: mongodb://127.0.0.1:27017
      PYTHONPATH: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install --no-cache-dir -r requirements.txt
          pip install pytest flake8 httpx

      - name: Lint backend with flake8
        run: |
          cd backend
          flake8 .

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..15}; do
            nc -z mongo 27017 && echo "MongoDB is up!" && break
            echo "Waiting for MongoDB... ($i/15)"
            sleep 5
          done

      - name: Check MongoDB health status
        run: |
          docker run --network host mongo:7.0 mongosh --host 127.0.0.1 --eval "db.adminCommand('ping')"

      - name: Run backend tests
        run: |
          cd backend
          pytest --maxfail=1 --disable-warnings -q

  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test-backend
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend and frontend images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/finance_backend ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/finance_frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/finance_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/finance_frontend